import Link from 'next/link';

export const metadata = { title: 'Threshold Technologies | Digital Solutions for Business' };

export default function Home() { return <main>
  <section className="hero"><div className="wrap"><p className="eyebrow">Threshold Technologies</p><h1>Building digital solutions for business</h1><p>We develop digital systems and software across multiple sectors — connecting data, engineering, commercial intelligence, and AI-assisted workflows.</p><div className="cta-row"><Link className="btn btn--primary" href="/contact">Build With Threshold <span className="arrow">→</span></Link><Link className="btn btn--ghost" href="/services">See What We Deliver</Link></div></div></section>
  <div className="wrap"><div className="sectors"><span>Construction</span><span>Transportation</span><span>Management</span><span>Finance</span><span>Digital Products</span></div></div>
  <section className="section"><div className="wrap"><div className="head"><p className="eyebrow">What is Threshold</p><h2>The line between business information and digital intelligence.</h2><p className="lede">A threshold is the point where something crosses over and changes state. We take raw information across structured engineering and AI until it becomes intelligence teams can decide and deliver with.</p></div><div className="threshold"><p className="threshold__cap">Information crossing the threshold</p><div className="threshold__track">{['Data','AI','Automation','Intelligence'].map((label, index) => <div className="node" key={label}><span className="node__n">0{index + 1}</span><span className="node__label">{label}</span></div>)}</div><p className="threshold__note">From raw data, through AI and automation, into commercial intelligence — the same path runs under every sector we work in.</p></div></div></section>
  <section className="section section--tight"><div className="wrap"><div className="grid grid--3">{[['About','Vision & mission','Why we build, and what we are working toward across every sector.','/about'],['Services','What we deliver','The capabilities and engagements available from Threshold today.','/services'],['Blog','The Product Lab','Software built in-house — products, progress, and where to find them.','/blog']].map(([tag,title,copy,href]) => <Link className="card" href={href} key={tag}><span className="card__tag">{tag}</span><h3>{title}</h3><p>{copy}</p></Link>)}</div></div></section>
</main>; }
