import Link from 'next/link';

export const metadata = { title: 'Threshold Technologies Holdings | Engineering, Technology & Digital Products' };

export default function Home() { return <main>
  <section className="hero"><div className="wrap"><p className="eyebrow">Threshold Technologies Holdings</p><h1>Engineering intelligence. Digital products. Applied technology.</h1><p>Threshold develops digital systems, engineering intelligence and applied technology through a connected ecosystem of engineering, research and product development.</p><div className="cta-row"><Link className="btn btn--primary" href="/contact">Build With Threshold <span className="arrow">→</span></Link><Link className="btn btn--ghost" href="/services">Explore the Ecosystem</Link></div></div></section>
  <div className="wrap"><div className="sectors"><span>Engineering</span><span>Technology</span><span>Research</span><span>AI</span><span>Digital Products</span></div></div>
  <section className="section"><div className="wrap"><div className="head"><p className="eyebrow">The Threshold Ecosystem</p><h2>One group. Three connected identities.</h2><p className="lede">Threshold Technologies Holdings connects engineering delivery, applied research and digital product development under one operating ecosystem.</p></div><div className="grid grid--3">
    <Link className="card" href="/about"><span className="card__tag">Threshold Technologies</span><h3>Technology & intelligence</h3><p>The group platform for digital systems, AI-assisted workflows, software and strategic technology development.</p></Link>
    <a className="card" href="https://modern-engineering-lab.netlify.app"><span className="card__tag">MEL</span><h3>Modern Engineering Lab</h3><p>Engineering × Technology × Research — multidisciplinary engineering, experimentation and applied research.</p></a>
    <a className="card" href="https://ths-studio-showroom.netlify.app"><span className="card__tag">THS Studio</span><h3>Digital products studio</h3><p>The product, experience and commercialisation studio for Threshold-built digital tools and technology products.</p></a>
  </div></div></section>
  <section className="section"><div className="wrap"><div className="head"><p className="eyebrow">What is Threshold</p><h2>The line between information and digital intelligence.</h2><p className="lede">A threshold is the point where something crosses over and changes state. We structure information, engineering knowledge and data so teams can review, decide and deliver with greater control.</p></div><div className="threshold"><p className="threshold__cap">Information crossing the threshold</p><div className="threshold__track">{['Data','AI','Automation','Intelligence'].map((label, index) => <div className="node" key={label}><span className="node__n">0{index + 1}</span><span className="node__label">{label}</span></div>)}</div><p className="threshold__note">From raw data, through AI and automation, into controlled intelligence — the same logic connects the work across Threshold, MEL and THS Studio.</p></div></div></section>
  <section className="section section--tight"><div className="wrap"><div className="grid grid--3">{[['About','Vision & mission','Why we build and how the Threshold ecosystem is structured.','/about'],['Services','What we deliver','Engineering, technology and digital capabilities available from Threshold.','/services'],['Products','Digital product portfolio','Software and digital products developed across the Threshold ecosystem.','/blog']].map(([tag,title,copy,href]) => <Link className="card" href={href} key={tag}><span className="card__tag">{tag}</span><h3>{title}</h3><p>{copy}</p></Link>)}</div></div></section>
</main>; }
